[tox]
envlist = py39, py310, py311, py312, py313, lint, mypy
isolated_build = True

[testenv]
description = Run test suite
extras = dev
commands =
    pytest {posargs:tests}

[testenv:lint]
description = Run ruff formatting and linting
extras = dev
commands =
    ruff format --check cpre tests
    ruff check cpre tests

[testenv:mypy]
description = Run mypy type checking
extras = dev
commands =
    mypy cpre
