"""Public package interface for cpre."""

from .api import (
    AnalysisError,
    AnalysisIncomplete,
    AnalysisOptions,
    AnalysisResult,
    ConditionError,
    ConditionalTree,
    ContextualSimplification,
    CpreError,
    ErrorCode,
    ExactSimplification,
    Finding,
    FindingKind,
    FixConfidence,
    MacroAssumptions,
    ParseError,
    SourceLocation,
    SourceRange,
    SuggestedEdit,
    analyze_source,
)

from .configuration import MacroConfiguration, UnknownNamePolicy
from .expansion import SourceMapping
from .macros import MacroDefinition, MacroEnvironment, MacroState
from .preprocessing import (
    PreprocessingContext,
    PreprocessDiagnostic,
    PreprocessResult,
    compact,
)
from .pragmas import (
    Pragma,
    PragmaDisposition,
    PragmaHandler,
    PragmaOrigin,
    preprocess_source,
)
from .structure import (
    ConditionalBlock,
    ConditionalBranch,
    ConditionalDirective,
    ConditionalStructureTree,
    DirectiveToken,
    StructuralSourceLocation,
    StructuralSourceRange,
    StructureDiagnostic,
    StructureDiagnosticCode,
    parse_conditionals,
)
from .symbolic import (
    BooleanAtom,
    Conjunction,
    Constant,
    DefinedVariable,
    Disjunction,
    Expression,
    FALSE,
    Negation,
    Predicate,
    TRUE,
    Variable,
    conjunction,
    disjunction,
    expression_from_dict,
    expression_predicates,
    expression_to_dict,
    format_expression,
    negate,
    normalize,
    ordered_atoms,
    simplify,
)

__version__ = "0.10.18"

__all__ = [
    "AnalysisError",
    "AnalysisIncomplete",
    "AnalysisOptions",
    "AnalysisResult",
    "BooleanAtom",
    "ConditionError",
    "ConditionalBlock",
    "ConditionalBranch",
    "ConditionalDirective",
    "ConditionalStructureTree",
    "ConditionalTree",
    "Conjunction",
    "Constant",
    "ContextualSimplification",
    "CpreError",
    "DefinedVariable",
    "DirectiveToken",
    "Disjunction",
    "ErrorCode",
    "ExactSimplification",
    "Expression",
    "FALSE",
    "Finding",
    "FindingKind",
    "FixConfidence",
    "MacroAssumptions",
    "MacroConfiguration",
    "MacroDefinition",
    "MacroEnvironment",
    "MacroState",
    "Negation",
    "ParseError",
    "Predicate",
    "Pragma",
    "PragmaDisposition",
    "PragmaHandler",
    "PragmaOrigin",
    "PreprocessingContext",
    "PreprocessDiagnostic",
    "PreprocessResult",
    "SourceLocation",
    "SourceMapping",
    "SourceRange",
    "StructuralSourceLocation",
    "StructuralSourceRange",
    "StructureDiagnostic",
    "StructureDiagnosticCode",
    "SuggestedEdit",
    "TRUE",
    "UnknownNamePolicy",
    "Variable",
    "__version__",
    "analyze_source",
    "compact",
    "conjunction",
    "disjunction",
    "expression_from_dict",
    "expression_predicates",
    "expression_to_dict",
    "format_expression",
    "negate",
    "normalize",
    "ordered_atoms",
    "parse_conditionals",
    "preprocess_source",
    "simplify",
]
