"""Public package interface for cpre."""

from .api import (
    AnalysisError,
    AnalysisIncomplete,
    AnalysisOptions,
    AnalysisResult,
    ConditionalTree,
    ConditionError,
    ContextualSimplification,
    CpreError,
    ErrorCode,
    ExactSimplification,
    Finding,
    FindingKind,
    FixConfidence,
    IncompleteComponent,
    IncompleteConfigurationError,
    IncompleteGroup,
    MacroAssumptions,
    ParseError,
    SourceLocation,
    SourceRange,
    SuggestedEdit,
    analyze_source,
)
from .configuration import MacroConfiguration, UnknownNamePolicy
from .expansion import SourceMapping
from .macro_analysis import (
    MacroAnalysisResult,
    MacroSimplificationResult,
    analyze_macro,
    analyze_macros,
    rewrite_macros,
    simplify_macros,
)
from .macros import MacroDefinition, MacroEnvironment, MacroState
from .pragmas import (
    Pragma,
    PragmaDisposition,
    PragmaHandler,
    PragmaOrigin,
    preprocess_source,
)
from .preprocessing import (
    PreprocessDiagnostic,
    PreprocessingContext,
    PreprocessResult,
    SkippedInclude,
    compact,
)
from .proofs import (
    ProofResult,
    SatisfiabilityResult,
    SimplificationResult,
    WitnessAssignment,
    WitnessAtomKind,
    WitnessResult,
    equivalent,
    exact_simplify,
    implies,
    satisfiable,
    witness_assignment,
)
from .structure import (
    ConditionalBlock,
    ConditionalBranch,
    ConditionalDirective,
    ConditionalStructureTree,
    DirectiveToken,
    StructuralSourceLocation,
    StructuralSourceRange,
    StructureDiagnostic,
    StructureDiagnosticCode,
    parse_conditionals,
)
from .symbolic import (
    FALSE,
    TRUE,
    BooleanAtom,
    Conjunction,
    Constant,
    DefinedVariable,
    Disjunction,
    Expression,
    Negation,
    Predicate,
    Variable,
    conjunction,
    disjunction,
    expression_from_dict,
    expression_predicates,
    expression_to_dict,
    format_expression,
    negate,
    normalize,
    ordered_atoms,
    simplify,
)
from .unknown_macros import MacroUse, UnknownMacro, unknown_macros, unknown_macros_in_source

# Single source of truth for the package version (Semantic Versioning 2.0.0).
# Every pull request merged to main bumps it once; see CONTRIBUTING.md.
__version__ = "0.21.2"

__all__ = [
    "AnalysisError",
    "AnalysisIncomplete",
    "AnalysisOptions",
    "AnalysisResult",
    "BooleanAtom",
    "ConditionError",
    "ConditionalBlock",
    "ConditionalBranch",
    "ConditionalDirective",
    "ConditionalStructureTree",
    "ConditionalTree",
    "Conjunction",
    "Constant",
    "ContextualSimplification",
    "CpreError",
    "DefinedVariable",
    "DirectiveToken",
    "Disjunction",
    "ErrorCode",
    "ExactSimplification",
    "Expression",
    "FALSE",
    "Finding",
    "FindingKind",
    "FixConfidence",
    "IncompleteComponent",
    "IncompleteConfigurationError",
    "IncompleteGroup",
    "MacroAnalysisResult",
    "MacroAssumptions",
    "MacroConfiguration",
    "MacroDefinition",
    "MacroEnvironment",
    "MacroSimplificationResult",
    "MacroState",
    "MacroUse",
    "Negation",
    "ParseError",
    "Predicate",
    "Pragma",
    "PragmaDisposition",
    "PragmaHandler",
    "PragmaOrigin",
    "PreprocessingContext",
    "PreprocessDiagnostic",
    "PreprocessResult",
    "ProofResult",
    "SatisfiabilityResult",
    "SimplificationResult",
    "SkippedInclude",
    "SourceLocation",
    "SourceMapping",
    "SourceRange",
    "StructuralSourceLocation",
    "StructuralSourceRange",
    "StructureDiagnostic",
    "StructureDiagnosticCode",
    "SuggestedEdit",
    "TRUE",
    "UnknownMacro",
    "UnknownNamePolicy",
    "Variable",
    "WitnessAssignment",
    "WitnessAtomKind",
    "WitnessResult",
    "__version__",
    "analyze_macro",
    "analyze_macros",
    "analyze_source",
    "compact",
    "conjunction",
    "disjunction",
    "equivalent",
    "exact_simplify",
    "expression_from_dict",
    "expression_predicates",
    "expression_to_dict",
    "format_expression",
    "implies",
    "negate",
    "normalize",
    "ordered_atoms",
    "parse_conditionals",
    "preprocess_source",
    "rewrite_macros",
    "satisfiable",
    "simplify",
    "simplify_macros",
    "unknown_macros",
    "unknown_macros_in_source",
    "witness_assignment",
]
